### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by evhumphrey** [Wolf-Fivousix/Full_Stack#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

- Good job! I left some feedback in the form of this issue. Please update it at your earliest convenience.
- For live messaging, look into ActionCable! Here's a non-exhaustive list on the topic:
  - [ActionCable and React](https://medium.com/@benpong89/action-cable-and-react-9a00be5e391b)
  - [Rails ActionCable](https://guides.rubyonrails.org/action_cable_overview.html) (This reading is a bit more dense, but provides some context. Not all of the info will be relevant, but parts will)

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

- CRUD can be your messages (creating them, viewing them, editing them, and deleting theme)

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- [x] All tables should be lowercased 

### `users` table 
- [x] Don't worry about friends at all as your MVPs (it can be a bonus); remove `friends_ids`
- [x] Avoid storing `servers_ids` in here. It should be a `many-to-many` relationship: a user can be in many servers, and a server can have many users. You'll need a `servers_memberships` join table, with a `user_id` and a `server_id`
- [x] I'd make your `email` unique, and `username` _not_ unique

_Edit_: 

- [x] It might be simpler to have both username && email unique

### `servers` table
- [x] I recommend ending all foreign keys with `_id`; I would have a column name `owner_id` instead of `owner`
- [x] Remove `channels` column

### `channels` table
- [x] Remove `messages_ids`; your messages should belong to a channel instead (a channel can have many messages, but a message cannot be in multiple channels)

### `messages` table
- [x] Add a `channel_id` foreign key for a `belongs-to` relationship
- [x] I would change `author` to `author_id`
- [x] The last table (`messages` duplicate?) on this document is not needed

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

### `users` slice

- [x] Remove `password_digest` and `session_token`
- [x] No need for `friends_id` slice of state
- Note that having a `servers_ids` array can work, but only use it if the orders of the servers matters in the UI

### `channels` slice 
- Note that having a `channels` array can work, but only use it if the orders of the channels matters in the UI. 

### `messages` slice
- (similar note with having arrays)

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

- [x] There should be an endpoint for root `/` so you can bootstrap the current user
- [x] You might not need a `GET /api/servers/:id` because you can fetch this when you fetch all the servers for the current user 
- [x] You probably won't need to fetch a single message `GET /api/messages/:id` (you'll likely fetch the messages when you fetch a single channel)

_Edit:_
- [x] You will need two endpoints (`POST` and `DELETE`) for joining and leaving a server (this will be for the `servers_memberships` table mentioned in schema section above)
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by Wolf-Fivousix** [comment]
All pending issues resolved.
Except for `GET /api/servers/:id` and `GET /api/messages/:id`. Pending implementation discussion before further action.

**Comment by Wolf-Fivousix** [comment]
All pending issues corrected. Closing issue request.
